==2019== Memcheck, a memory error detector
==2019== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==2019== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==2019== Command: ./cub3d maps/map_example.cub
==2019== Parent PID: 2018
==2019== 
==2019== Invalid read of size 8
==2019==    at 0x10A11D: line_too_long (parser_texture.c:24)
==2019==    by 0x109E64: parser_map_line (parser_map.c:137)
==2019==    by 0x1096AD: cub3d_parse_map (cub3d_map_rules.c:85)
==2019==    by 0x109406: cub3d_read_map (cub3d_read_map.c:36)
==2019==    by 0x1092F3: main (cub3d.c:23)
==2019==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==2019== 
==2019== 
==2019== Process terminating with default action of signal 11 (SIGSEGV)
==2019==  Access not within mapped region at address 0x0
==2019==    at 0x10A11D: line_too_long (parser_texture.c:24)
==2019==    by 0x109E64: parser_map_line (parser_map.c:137)
==2019==    by 0x1096AD: cub3d_parse_map (cub3d_map_rules.c:85)
==2019==    by 0x109406: cub3d_read_map (cub3d_read_map.c:36)
==2019==    by 0x1092F3: main (cub3d.c:23)
==2019==  If you believe this happened as a result of a stack
==2019==  overflow in your program's main thread (unlikely but
==2019==  possible), you can try to increase the size of the
==2019==  main thread stack using the --main-stacksize= flag.
==2019==  The main thread stack size used in this run was 8388608.
==2019== 
==2019== HEAP SUMMARY:
==2019==     in use at exit: 14 bytes in 3 blocks
==2019==   total heap usage: 15 allocs, 12 frees, 83 bytes allocated
==2019== 
==2019== 1 bytes in 1 blocks are still reachable in loss record 1 of 3
==2019==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==2019==    by 0x10A2E8: ft_calloc (in /root/cub3d/cub3d)
==2019==    by 0x109660: cub3d_parse_map (cub3d_map_rules.c:79)
==2019==    by 0x109406: cub3d_read_map (cub3d_read_map.c:36)
==2019==    by 0x1092F3: main (cub3d.c:23)
==2019== 
==2019== 1 bytes in 1 blocks are still reachable in loss record 2 of 3
==2019==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==2019==    by 0x10A9DE: save_remains (in /root/cub3d/cub3d)
==2019==    by 0x10ABAE: get_next_line (in /root/cub3d/cub3d)
==2019==    by 0x10966E: cub3d_parse_map (cub3d_map_rules.c:80)
==2019==    by 0x109406: cub3d_read_map (cub3d_read_map.c:36)
==2019==    by 0x1092F3: main (cub3d.c:23)
==2019== 
==2019== 12 bytes in 1 blocks are still reachable in loss record 3 of 3
==2019==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==2019==    by 0x10A893: strcat_result (in /root/cub3d/cub3d)
==2019==    by 0x10AB75: get_next_line (in /root/cub3d/cub3d)
==2019==    by 0x10966E: cub3d_parse_map (cub3d_map_rules.c:80)
==2019==    by 0x109406: cub3d_read_map (cub3d_read_map.c:36)
==2019==    by 0x1092F3: main (cub3d.c:23)
==2019== 
==2019== LEAK SUMMARY:
==2019==    definitely lost: 0 bytes in 0 blocks
==2019==    indirectly lost: 0 bytes in 0 blocks
==2019==      possibly lost: 0 bytes in 0 blocks
==2019==    still reachable: 14 bytes in 3 blocks
==2019==         suppressed: 0 bytes in 0 blocks
==2019== 
==2019== For lists of detected and suppressed errors, rerun with: -s
==2019== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
